/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prograiii_proyectoi;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Karlenypc
 */
public class VentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public static ListaDoble lista = new ListaDoble();

    public VentanaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionMecanismo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtnAleatorio = new javax.swing.JRadioButton();
        rbtnArchivotxt = new javax.swing.JRadioButton();
        txtMecanismo = new javax.swing.JLabel();
        txtRango1 = new javax.swing.JLabel();
        txtRango2 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();
        txtRango3 = new javax.swing.JLabel();
        txtRango4 = new javax.swing.JLabel();
        jRadio100a1000 = new javax.swing.JRadioButton();
        jRadio1a100 = new javax.swing.JRadioButton();
        jRadio1000a10000 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionMecanismo.add(rbtnAleatorio);
        rbtnAleatorio.setText("1. De forma aleatoria");
        rbtnAleatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnAleatorioMouseClicked(evt);
            }
        });
        rbtnAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAleatorioActionPerformed(evt);
            }
        });

        seleccionMecanismo.add(rbtnArchivotxt);
        rbtnArchivotxt.setText("2. Cargar mediante un  archivo de texto");
        rbtnArchivotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnArchivotxtMouseClicked(evt);
            }
        });
        rbtnArchivotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnArchivotxtActionPerformed(evt);
            }
        });

        txtMecanismo.setText("Seleccione un mecanismo:");

        txtRango1.setText("Ingrese el rango que desea:");
        txtRango1.setEnabled(false);

        txtRango2.setText("100 - 1000");
        txtRango2.setEnabled(false);

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        txtRango3.setText("1 - 100");
        txtRango3.setEnabled(false);

        txtRango4.setText("1000-10000");
        txtRango4.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(rbtnArchivotxt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addComponent(btnGenerar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtRango1)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jRadio1a100)
                                            .addComponent(txtRango3))
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(txtRango2)
                                                .addGap(18, 18, 18)
                                                .addComponent(txtRango4))
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(36, 36, 36)
                                                .addComponent(jRadio100a1000)
                                                .addGap(48, 48, 48)
                                                .addComponent(jRadio1000a10000))))))
                            .addComponent(rbtnAleatorio)
                            .addComponent(txtMecanismo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtMecanismo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnAleatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRango1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRango2)
                    .addComponent(txtRango4)
                    .addComponent(txtRango3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addComponent(btnGenerar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadio100a1000)
                            .addComponent(jRadio1a100)
                            .addComponent(jRadio1000a10000))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(rbtnArchivotxt)))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(203, 203, 203)
                    .addComponent(jRadioButton3)
                    .addContainerGap(203, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addComponent(jRadioButton3)
                    .addContainerGap(136, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnAleatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnAleatorioMouseClicked
        // TODO add your handling code here:
        this.txtRango3.setEnabled(true);
        this.txtRango4.setEnabled(true);
        this.txtRango2.setEnabled(true);
        this.jRadio1a100.setEnabled(true);
        this.jRadio100a1000.setEnabled(true);
        this.jRadio1000a10000.setEnabled(true);
    }//GEN-LAST:event_rbtnAleatorioMouseClicked

    private void rbtnAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAleatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAleatorioActionPerformed

    private void rbtnArchivotxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnArchivotxtMouseClicked
        // TODO add your handling code here:
        this.txtRango3.setEnabled(false);
        this.txtRango4.setEnabled(false);
        this.txtRango2.setEnabled(false);
        this.jRadio1a100.setEnabled(false);
        this.jRadio100a1000.setEnabled(false);
        this.jRadio1000a10000.setEnabled(false);
    }//GEN-LAST:event_rbtnArchivotxtMouseClicked

    private void rbtnArchivotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnArchivotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnArchivotxtActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        ObtenerListaNumeros obt = new ObtenerListaNumeros();
        if (rbtnAleatorio.isSelected()) {
            if (jRadio1a100.isSelected()) {
                lista = obt.generarAleatorio(100, 1);
            } else if (jRadio100a1000.isSelected()) {
                lista = obt.generarAleatorioRangoMayor(1000, 100);
            } else if (jRadio1000a10000.isSelected()) {
                lista = obt.generarAleatorioRangoMayor(10000, 1000);
            }

        } else if (rbtnArchivotxt.isSelected()) {
            JFileChooser fichero = new JFileChooser();
            int seleccion = fichero.showOpenDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {

                File fich = fichero.getSelectedFile();
                lista = obt.insetarFile(fich.getAbsolutePath());

            }

        }

        VentanaPrincipal v = new VentanaPrincipal();
        v.lista = lista.clonarLista(lista);
        v.mostrarIteracionList = v.lista.mostrarIteracion();
        v.jTextshowList.setText(v.mostrarIteracionList);
        //v.lista.mostrar();
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadio1000a10000;
    private javax.swing.JRadioButton jRadio100a1000;
    private javax.swing.JRadioButton jRadio1a100;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton rbtnAleatorio;
    private javax.swing.JRadioButton rbtnArchivotxt;
    private javax.swing.ButtonGroup seleccionMecanismo;
    private javax.swing.JLabel txtMecanismo;
    private javax.swing.JLabel txtRango1;
    private javax.swing.JLabel txtRango2;
    private javax.swing.JLabel txtRango3;
    private javax.swing.JLabel txtRango4;
    // End of variables declaration//GEN-END:variables
}
