/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prograiii_proyectoi;

import javax.swing.JOptionPane;

/**
 *
 * @author Karlenypc
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    //VentanaInicial vI = new VentanaInicial();
    MetodoOrdenamiento bubbleSort = new MetodoOrdenamiento();
    public static ListaDoble lista = new ListaDoble();
    public static String mostrarIteracionList = "";
    public static String mostrarIteracionBusqueda = "";

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setVisible(true);
        //VentanaInicial vI = new VentanaInicial(this, false);
        //vI.setVisible(true);

        //this.lista = vI.lista.;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jbtnOrdenamiento = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextshowList = new javax.swing.JTextArea();
        jbtnBusqueda = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MainWindow");

        jPanel1.setBackground(new java.awt.Color(100, 105, 72));

        jbtnOrdenamiento.setBackground(new java.awt.Color(238, 235, 219));
        jbtnOrdenamiento.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jbtnOrdenamiento.setForeground(new java.awt.Color(43, 36, 32));
        jbtnOrdenamiento.setText("Aplicar Ordenamiento BubbleSort");
        jbtnOrdenamiento.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtnOrdenamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnOrdenamientoActionPerformed(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(43, 36, 32));
        jScrollPane1.setForeground(new java.awt.Color(43, 36, 32));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(43, 36, 32)));
        jScrollPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jTextshowList.setBackground(new java.awt.Color(238, 235, 219));
        jTextshowList.setColumns(20);
        jTextshowList.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jTextshowList.setForeground(new java.awt.Color(28, 24, 21));
        jTextshowList.setRows(5);
        jTextshowList.setCaretColor(new java.awt.Color(28, 24, 21));
        jTextshowList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextshowListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTextshowList);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 463, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jbtnBusqueda.setBackground(new java.awt.Color(238, 235, 219));
        jbtnBusqueda.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        jbtnBusqueda.setForeground(new java.awt.Color(43, 36, 32));
        jbtnBusqueda.setText("Realizar Busqueda");
        jbtnBusqueda.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jbtnBusqueda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBusquedaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jbtnOrdenamiento, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jbtnBusqueda)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnOrdenamiento)
                    .addComponent(jbtnBusqueda))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnOrdenamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnOrdenamientoActionPerformed
        long TInicio, TFin, tiempo; //Variables para determinar el tiempo de ejecución
        TInicio = System.currentTimeMillis(); //Tomamos la hora en que inicio el algoritmo y la almacenamos en la variable inicio        // TODO add your handling code here:
        mostrarIteracionList = bubbleSort.bubbleSortIteraciones(lista);
        TFin = System.currentTimeMillis(); //Tomamos la hora en que finalizó el algoritmo y la almacenamos en la variable T
        tiempo = TFin - TInicio; //Calculamos los milisegundos de diferencia
        jTextshowList.append(mostrarIteracionList + "\n" + "El proceso de ordenamiento ha demorado " + tiempo + " milisegudos");
    }//GEN-LAST:event_jbtnOrdenamientoActionPerformed

    private void jTextshowListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextshowListMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextshowListMouseClicked

    private void jbtnBusquedaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBusquedaActionPerformed
        // TODO add your handling code here:
        Busqueda bus = new Busqueda();
        int busq = 0;
        int seleccion = JOptionPane.showOptionDialog(null, "Seleccione una opcion de busqueda", "Tipo de Busqueda", JOptionPane.YES_NO_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE, null, new Object[]{"Busqueda Secuencial", "Busqueda Binaria", "Busqueda por Interpolacion", "Busqueda por Hash"}, "Busqueda Secuencial");
        switch (seleccion + 1) {
            case 1:
                busq = Integer.parseInt(JOptionPane.showInputDialog(this, "Que numero desea buscar"));
                bus.busquedaSecuencial(lista, busq);
                break;
            case 2:
                busq = Integer.parseInt(JOptionPane.showInputDialog(this, "Que numero desea buscar"));
                bus.busquedaBinaria(lista, busq);
                break;
            case 3:
                busq = Integer.parseInt(JOptionPane.showInputDialog(this, "Que numero desea buscar"));
                bus.busquedaInterpolacion(lista, busq);
                break;
            case 4:
                busq = Integer.parseInt(JOptionPane.showInputDialog(this, "Que numero desea buscar"));
                Busquedasearch hash = new Busquedasearch(lista.getLargo());
                String busqueda = Integer.toString(busq);
                hash.busquedaHash(busqueda, lista);

        }

        mostrarIteracionList = lista.mostrarIteracion();
        if (seleccion == 0) {
            mostrarIteracionBusqueda = bus.busquedaSecuencialIteracion(lista, busq);
        } else if (seleccion == 1) {
           
        } else if (seleccion == 2) {
            mostrarIteracionBusqueda = bus.busquedaInterpolacionIteraccion(lista, busq);
        } else if (seleccion == 3) {
            
        }
       
        jTextshowList.setText("RESUMEN LISTA ORDENADA : \n" + "\n" + mostrarIteracionList + "\n***Metodo Ordenamiento***\n" + "\n" + mostrarIteracionBusqueda);

    }//GEN-LAST:event_jbtnBusquedaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTextArea jTextshowList;
    private javax.swing.JButton jbtnBusqueda;
    private javax.swing.JButton jbtnOrdenamiento;
    // End of variables declaration//GEN-END:variables
}
