/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prograiii_proyectoi;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Karlenypc
 */
public class VentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public static ListaDoble lista = new ListaDoble();

    public VentanaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionMecanismo = new javax.swing.ButtonGroup();
        seleccionRango = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnGenerar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        txtMecanismo = new javax.swing.JLabel();
        rbtnAleatorio = new javax.swing.JRadioButton();
        txtRango = new javax.swing.JLabel();
        txtRango1 = new javax.swing.JLabel();
        txtRango2 = new javax.swing.JLabel();
        txtRango3 = new javax.swing.JLabel();
        jRadio1a100 = new javax.swing.JRadioButton();
        jRadio100a1000 = new javax.swing.JRadioButton();
        jRadio1000a10000 = new javax.swing.JRadioButton();
        rbtnArchivotxt = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(100, 105, 72));

        btnGenerar.setBackground(new java.awt.Color(238, 235, 219));
        btnGenerar.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        btnGenerar.setForeground(new java.awt.Color(43, 36, 32));
        btnGenerar.setText("Generar");
        btnGenerar.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(238, 235, 219));

        txtMecanismo.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        txtMecanismo.setForeground(new java.awt.Color(28, 24, 21));
        txtMecanismo.setText("Seleccione un mecanismo:");

        seleccionMecanismo.add(rbtnAleatorio);
        rbtnAleatorio.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        rbtnAleatorio.setForeground(new java.awt.Color(28, 24, 21));
        rbtnAleatorio.setText("1. De forma aleatoria");
        rbtnAleatorio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        rbtnAleatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnAleatorioMouseClicked(evt);
            }
        });
        rbtnAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAleatorioActionPerformed(evt);
            }
        });

        txtRango.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        txtRango.setForeground(new java.awt.Color(28, 24, 21));
        txtRango.setText("Ingrese el rango que desea:");

        txtRango1.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        txtRango1.setForeground(new java.awt.Color(28, 24, 21));
        txtRango1.setText("1 - 100");
        txtRango1.setEnabled(false);

        txtRango2.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        txtRango2.setForeground(new java.awt.Color(28, 24, 21));
        txtRango2.setText("100 - 1000");
        txtRango2.setEnabled(false);

        txtRango3.setFont(new java.awt.Font("Malgun Gothic", 0, 12)); // NOI18N
        txtRango3.setForeground(new java.awt.Color(28, 24, 21));
        txtRango3.setText("1000-10000");
        txtRango3.setEnabled(false);

        seleccionRango.add(jRadio1a100);

        seleccionRango.add(jRadio100a1000);

        seleccionRango.add(jRadio1000a10000);

        seleccionMecanismo.add(rbtnArchivotxt);
        rbtnArchivotxt.setFont(new java.awt.Font("Malgun Gothic", 1, 12)); // NOI18N
        rbtnArchivotxt.setForeground(new java.awt.Color(43, 36, 32));
        rbtnArchivotxt.setText("2. Cargar mediante un  archivo de texto");
        rbtnArchivotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnArchivotxtMouseClicked(evt);
            }
        });
        rbtnArchivotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnArchivotxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtMecanismo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnArchivotxt)
                            .addComponent(txtRango)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jRadio1a100)
                                    .addComponent(txtRango1))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRango2)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtRango3))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(36, 36, 36)
                                        .addComponent(jRadio100a1000)
                                        .addGap(48, 48, 48)
                                        .addComponent(jRadio1000a10000))))
                            .addComponent(rbtnAleatorio))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtMecanismo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnAleatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRango, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtRango2)
                    .addComponent(txtRango3)
                    .addComponent(txtRango1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRadio100a1000)
                    .addComponent(jRadio1a100)
                    .addComponent(jRadio1000a10000))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbtnArchivotxt)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(btnGenerar, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnGenerar, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnAleatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnAleatorioMouseClicked
        // TODO add your handling code here:
        this.txtRango1.setEnabled(true);
        this.txtRango3.setEnabled(true);
        this.txtRango2.setEnabled(true);
        this.jRadio1a100.setEnabled(true);
        this.jRadio100a1000.setEnabled(true);
        this.jRadio1000a10000.setEnabled(true);
    }//GEN-LAST:event_rbtnAleatorioMouseClicked

    private void rbtnAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAleatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAleatorioActionPerformed

    private void rbtnArchivotxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnArchivotxtMouseClicked
        // TODO add your handling code here:
        this.txtRango1.setEnabled(false);
        this.txtRango3.setEnabled(false);
        this.txtRango2.setEnabled(false);
        this.jRadio1a100.setEnabled(false);
        this.jRadio100a1000.setEnabled(false);
        this.jRadio1000a10000.setEnabled(false);
    }//GEN-LAST:event_rbtnArchivotxtMouseClicked

    private void rbtnArchivotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnArchivotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnArchivotxtActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        ObtenerListaNumeros obt = new ObtenerListaNumeros();
        if (rbtnAleatorio.isSelected()) {
            if (jRadio1a100.isSelected()) {
                lista = obt.generarAleatorio(100, 1);
            } else if (jRadio100a1000.isSelected()) {
                lista = obt.generarAleatorioRangoMayor(1000, 100);
            } else if (jRadio1000a10000.isSelected()) {
                lista = obt.generarAleatorioRangoMayor(10000, 1000);
            }

        } else if (rbtnArchivotxt.isSelected()) {
            JFileChooser fichero = new JFileChooser();
            int seleccion = fichero.showOpenDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {

                File fich = fichero.getSelectedFile();
                lista = obt.insetarFile(fich.getAbsolutePath());

            }

        }

        VentanaPrincipal v = new VentanaPrincipal();
        v.lista = lista.clonarLista(lista);
        v.mostrarIteracionList = v.lista.mostrarIteracion();
        v.jTextshowList.setText(v.mostrarIteracionList);
        //v.lista.mostrar();
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton jRadio1000a10000;
    private javax.swing.JRadioButton jRadio100a1000;
    private javax.swing.JRadioButton jRadio1a100;
    private javax.swing.JRadioButton rbtnAleatorio;
    private javax.swing.JRadioButton rbtnArchivotxt;
    private javax.swing.ButtonGroup seleccionMecanismo;
    private javax.swing.ButtonGroup seleccionRango;
    private javax.swing.JLabel txtMecanismo;
    private javax.swing.JLabel txtRango;
    private javax.swing.JLabel txtRango1;
    private javax.swing.JLabel txtRango2;
    private javax.swing.JLabel txtRango3;
    // End of variables declaration//GEN-END:variables
}
