/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prograiii_proyectoi;

import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author Karlenypc
 */
public class VentanaInicial extends javax.swing.JFrame {

    /**
     * Creates new form VentanaInicial
     */
    public static ListaDoble lista = new ListaDoble();

    public VentanaInicial() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        seleccionMecanismo = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        rbtnAleatorio = new javax.swing.JRadioButton();
        rbtnArchivotxt = new javax.swing.JRadioButton();
        txtMecanismo = new javax.swing.JLabel();
        jFieldRango = new javax.swing.JTextField();
        txtRango1 = new javax.swing.JLabel();
        txtRango2 = new javax.swing.JLabel();
        btnGenerar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        seleccionMecanismo.add(rbtnAleatorio);
        rbtnAleatorio.setText("1. De forma aleatoria");
        rbtnAleatorio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnAleatorioMouseClicked(evt);
            }
        });
        rbtnAleatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnAleatorioActionPerformed(evt);
            }
        });

        seleccionMecanismo.add(rbtnArchivotxt);
        rbtnArchivotxt.setText("2. Cargar mediante un  archivo de texto");
        rbtnArchivotxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbtnArchivotxtMouseClicked(evt);
            }
        });
        rbtnArchivotxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnArchivotxtActionPerformed(evt);
            }
        });

        txtMecanismo.setText("Seleccione un mecanismo:");

        jFieldRango.setEnabled(false);
        jFieldRango.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFieldRangoActionPerformed(evt);
            }
        });

        txtRango1.setText("Ingrese el rango que desea:");
        txtRango1.setEnabled(false);

        txtRango2.setText("Entre  1   y...");
        txtRango2.setEnabled(false);

        btnGenerar.setText("Generar");
        btnGenerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rbtnAleatorio)
                            .addComponent(txtMecanismo, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtnArchivotxt)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txtRango2)
                                        .addGap(18, 18, 18)
                                        .addComponent(jFieldRango, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtRango1))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(245, 245, 245)
                        .addComponent(btnGenerar)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(txtMecanismo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(rbtnAleatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtRango1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFieldRango, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRango2))
                .addGap(18, 18, 18)
                .addComponent(rbtnArchivotxt)
                .addGap(18, 18, 18)
                .addComponent(btnGenerar)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rbtnAleatorioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnAleatorioMouseClicked
        // TODO add your handling code here:
        this.txtRango1.setEnabled(true);
        this.txtRango2.setEnabled(true);
        this.jFieldRango.setEnabled(true);
    }//GEN-LAST:event_rbtnAleatorioMouseClicked

    private void rbtnAleatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnAleatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnAleatorioActionPerformed

    private void rbtnArchivotxtMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbtnArchivotxtMouseClicked
        // TODO add your handling code here:
        this.txtRango1.setEnabled(false);
        this.txtRango2.setEnabled(false);
        this.jFieldRango.setEnabled(false);
    }//GEN-LAST:event_rbtnArchivotxtMouseClicked

    private void rbtnArchivotxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnArchivotxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnArchivotxtActionPerformed

    private void jFieldRangoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFieldRangoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFieldRangoActionPerformed

    private void btnGenerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarActionPerformed
        // TODO add your handling code here:
        ObtenerListaNumeros obt = new ObtenerListaNumeros();
        if (rbtnAleatorio.isSelected()) {
            String obtenerRango = jFieldRango.getText();
            int rango = Integer.parseInt(obtenerRango);
            lista = obt.generarAleatorio(rango);

        } else if (rbtnArchivotxt.isSelected()) {
            JFileChooser fichero = new JFileChooser();
            int seleccion = fichero.showOpenDialog(this);

            if (seleccion == JFileChooser.APPROVE_OPTION) {

                File fich = fichero.getSelectedFile();
                lista = obt.insetarFile(fich.getAbsolutePath());

            }

        }

        VentanaPrincipal v = new VentanaPrincipal();
        v.lista = lista.clonarLista(lista);
        v.mostrarIteracionList = v.lista.mostrarIteracion();
        v.jTextshowList.setText(v.mostrarIteracionList);
        //v.lista.mostrar();
        this.setVisible(false);
    }//GEN-LAST:event_btnGenerarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicial.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaInicial().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGenerar;
    private javax.swing.JTextField jFieldRango;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton rbtnAleatorio;
    private javax.swing.JRadioButton rbtnArchivotxt;
    private javax.swing.ButtonGroup seleccionMecanismo;
    private javax.swing.JLabel txtMecanismo;
    private javax.swing.JLabel txtRango1;
    private javax.swing.JLabel txtRango2;
    // End of variables declaration//GEN-END:variables
}
